################################################################################
# Nginx Compose
################################################################################
# docker compose -f docker-compose.yml up -d
################################################################################
version: "3.7"

services:
  web:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - /opt/nginx/nginx:/etc/nginx
